// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orgtxrsagsbeexaafjya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZ3R4cnNhZ3NiZWV4YWFmanlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTY0NjksImV4cCI6MjA3MDM3MjQ2OX0.G_EV3LPsoj9vsQhZorW9BXm_jhcAxmWVIo3xPwdGnK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});